name: 'Claude Discussion Bot'
description: 'Interact with Claude Code through GitHub Discussions'

inputs:
  anthropic_api_key:
    description: 'Anthropic API Key'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true
  discussion_id:
    description: 'Discussion ID'
    required: true
  is_comment:
    description: 'Whether this is a comment (true) or new discussion (false)'
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'