name: 'Claude Code Test Fixer'
description: 'Automatically fixes failed tests using Claude Code'

inputs:
  anthropic_api_key:
    description: 'Anthropic API Key'
    required: true
  test_logs:
    description: 'Test failure logs'
    required: true
  branch_name:
    description: 'Branch name to fix'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'