name: Auto Fix Failed Tests

on:
  workflow_run:
    workflows: ["CI Tests"]
    types: [completed]

jobs:
  auto-fix:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      actions: read
      checks: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          
      - name: Get test logs
        uses: actions/github-script@v7
        id: get-logs
        with:
          script: |
            const runId = context.payload.workflow_run.id;
            const { data: jobs } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            });
            
            let testLogs = '';
            for (const job of jobs.jobs) {
              if (job.conclusion === 'failure') {
                const { data: logs } = await github.rest.actions.downloadJobLogsForWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  job_id: job.id
                });
                testLogs += logs;
              }
            }
            
            return testLogs;
            
      - name: Fix tests with Claude Code
        uses: ./claude-code-test-fixer
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          test_logs: ${{ steps.get-logs.outputs.result }}
          branch_name: ${{ github.event.workflow_run.head_branch }}